services:
  whirlpool:
    image: whirlpool-standalone
    container_name: whirlpool-standalone
    extends:
      file: ../../../viridian/algae/docker/compose.base.yml
      service: whirlpool
    build:
      target: default-certified
      args:
        SEASIDE_ADDRESS: ${SEASIDE_HOST_ADDRESS}
    networks:
      sea-net:
        ipv4_address: 10.1.0.87


networks:
  sea-net:
    ipam:
      config:
        - subnet: 10.1.0.0/24
          gateway: 10.1.0.1
