services:
  algae:
    extends:
      file: compose.base.yml
      service: algae
    build:
      args:
        NETWORK_GATEWAY: 10.65.0.100
    environment:
      RESTRICTED_ADDRESS: 8.8.4.4
      SEASIDE_ADDRESS: 10.87.65.87
      VPN_COMMAND: python3 -m pytest --log-cli-level=$$LOGGING_LEVEL tests/test_integration_*.py
    networks:
      sea-client:
        ipv4_address: 10.65.0.65
    depends_on:
      whirlpool:
        condition: service_healthy
      router:
        condition: service_started

  router:
    extends:
      file: compose.base.yml
      service: router
    build:
      args:
        RESTRICTED_ADDRESS: 8.8.4.4
    networks:
      sea-client:
        ipv4_address: 10.65.0.100
      sea-router:
        ipv4_address: 10.87.65.100

  whirlpool:
    extends:
      file: compose.base.yml
      service: whirlpool
    build:
      args:
        NETWORK_GATEWAY: 10.87.42.1
        SEASIDE_ADDRESS: 10.87.65.87
    environment:
      SEASIDE_EXTERNAL: 10.87.42.87
    networks:
      sea-router:
        ipv4_address: 10.87.65.87
      sea-server:
        ipv4_address: 10.87.42.87


networks:
  sea-client:
    ipam:
      config:
        - subnet: 10.65.0.0/24
          gateway: 10.65.0.1
  sea-router:
    ipam:
      config:
        - subnet: 10.87.65.0/24
          gateway: 10.87.65.1
  sea-server:
    ipam:
      config:
        - subnet: 10.87.42.0/24
          gateway: 10.87.42.1
