version: "3.9"

services:
  algae:
    image: seaside-algae-test
    container_name: seaside-algae
    privileged: true
    build:
      dockerfile: Dockerfile.algae
      target: test
    environment:
      LOG_LEVEL: DEBUG
      BUFFER_SIZE: 8192  # Buffer for echo server message storing
      LOCAL_ECHO_PORT: 5000  # Port for echo server accessing
      OWNER_KEY: SuperSafeNodeOwnerKey:142  # Whirlpool node owner key

  whirlpool:
    image: seaside-whirlpool-test
    container_name: seaside-whirlpool
    privileged: true
    build:
      dockerfile: Dockerfile.whirlpool
      target: test
    environment:
      LOG_LEVEL: DEBUG
      OWNER_KEY: SuperSafeNodeOwnerKey:142  # Whirlpool node owner key

  echo:
    image: seaside-echo-test
    container_name: seaside-echo
    privileged: true
    build:
      dockerfile: Dockerfile.echo
      target: test
    environment:
      LOG_LEVEL: DEBUG
      BUFFER_SIZE: 8192  # Buffer for echo server message storing
      ECHO_PORT: 5000  # Port for echo server accessing

  router:
    image: seaside-router-test
    privileged: true
    build:
      dockerfile: Dockerfile.router
      target: test
