version: "3.9"

services:
  algae:
    extends:
      file: compose.base.yml
      service: algae
    environment:
      NODE_ADDR: 87.0.0.87
      LOCAL_ADDR: 87.0.0.65
      LOCAL_ECHO: 69.0.0.69
    networks:
      sea-int:
        ipv4_address: 87.0.0.65
    depends_on:
      whirlpool:
        condition: service_healthy
      echo:
        condition: service_healthy

  whirlpool:
    extends:
      file: compose.base.yml
      service: whirlpool
    environment:
      ADDRESS: 87.0.0.87
      EXTERNAL: 69.0.0.87
    networks:
      sea-int:
        ipv4_address: 87.0.0.87
      sea-ext:
        ipv4_address: 69.0.0.87

  echo:
    extends:
      file: compose.base.yml
      service: echo
    networks:
      sea-ext:
        ipv4_address: 69.0.0.69

networks:
  sea-int:
    internal: true
    ipam:
      config:
        - subnet: 87.0.0.0/24
          gateway: 87.0.0.1
  sea-ext:
    internal: true
    ipam:
      config:
        - subnet: 69.0.0.0/24
          gateway: 69.0.0.1
