services:
  algae:
    extends:
      file: compose.base.yml
      service: algae
    build:
      target: default
    environment:
      VPN_COMMAND: python3 -m pytest --log-cli-level=$$LOGGING_LEVEL tests/test_unit_*.py
