# This file defines basic Docker images for integration testing.
# Unlike images from "default", these contain additional dependencies, settings, etc.
# They also will not be destroyed and recreated during tests - for speedup.
# They are also reused in other Dockerfile targets in this directory.

name: seaside-algae-base

services:
  algae:
    image: seaside-algae
    privileged: true
    init: true
    build:
      dockerfile: viridian/algae/docker/Dockerfile.algae
      context: ../../..
      target: default-routed
    env_file:
      - test.conf.env
    environment:
      RUNNING_IN_CI: ${RUNNING_IN_CI:-0}
      SEASIDE_ROOT_CERTIFICATE_AUTHORITY: /seaside/viridian/ca/rootCA.crt
    dns:
      - 1.1.1.1
      - 8.8.8.8
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - ../certificates/viridian:/seaside/viridian/ca:ro

  whirlpool:
    image: seaside-whirlpool
    container_name: seaside-whirlpool
    privileged: true
    init: true
    build:
      dockerfile: caerulean/whirlpool/Dockerfile
      context: ../../..
      target: default-routed
    env_file:
      - test.conf.env
    environment:
      RUNNING_IN_CI: ${RUNNING_IN_CI:-0}
      SEASIDE_PRIVATE_KEY: LLFLPRfCNNCe21xZKIUvZuwB7iaN18/szKNrCAbBAaHGfN32cZlSog==
      SEASIDE_SERVER_KEY: c2VjcmV0IGVuY29kZWQgYmFzZTY0IHNlcnZlciBrZXk=
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - ../certificates/caerulean:/seaside/caerulean/certificates:ro

  echo:
    image: seaside-echo
    container_name: seaside-echo
    privileged: true
    init: true
    build:
      dockerfile: Dockerfile.echo
      target: default-routed
    env_file:
      - test.conf.env
    environment:
      LOG_LEVEL: DEBUG

  router:
    image: seaside-router
    container_name: seaside-router
    privileged: true
    init: true
    build:
      dockerfile: Dockerfile.router
      target: default
