name: seaside-algae-domain

services:
  algae:
    image: seaside-algae-smoke-domain
    container_name: seaside-algae
    privileged: true
    build:
      dockerfile: viridian/algae/docker/Dockerfile.algae
      context: ../../..
      target: commanded
      args:
        NETWORK_GATEWAY: 10.0.0.100
        COMMAND: dig +short google.com
    env_file:
      - test.conf.env
    environment:
      SEASIDE_ADDRESS: 10.0.0.87
      SEASIDE_ROOT_CERTIFICATE_AUTHORITY: /seaside/viridian/ca/rootCA.crt
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - ../certificates/viridian:/seaside/viridian/ca:ro
    networks:
      sea-net:
        ipv4_address: 10.0.0.65
    depends_on:
      whirlpool:
        condition: service_healthy

  whirlpool:
    image: seaside-whirlpool-smoke-domain
    extends:
      file: compose.base.yml
      service: whirlpool
    build:
      args:
        NETWORK_GATEWAY: 10.0.0.1
    environment:
      SEASIDE_ADDRESS: 10.0.0.87
      SEASIDE_EXTERNAL: 10.0.0.87
    networks:
      sea-net:
        ipv4_address: 10.0.0.87


networks:
  sea-net:
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
