services:
  whirlpool-base:
    image: whirlpool-standalone
    container_name: whirlpool-standalone
    extends:
      file: compose.base.yml
      service: whirlpool-base
    build:
      target: default-certified
      args:
        SEASIDE_ADDRESS: ${SEASIDE_HOST_ADDRESS}

  whirlpool-bridge:
    extends: whirlpool-base
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    networks:
      sea-net:
        ipv4_address: 10.0.0.87

  whirlpool-host:
    extends: whirlpool-base
    network_mode: host
    healthcheck:
      test: ["CMD", "netstat -tulpn | grep -q \":$SEASIDE_CTRLPORT\""]
      interval: 10s
      timeout: 1s
      retries: 3
      start-period: 15s


networks:
  sea-net:
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
