version: "3.9"

services:
  algae:
    extends:
      file: compose.base.yml
      service: algae
    environment:
      BUFFER_SIZE: 8192
      NODE_ADDR: 10.0.0.87
      LOCAL_ECHO: 10.0.0.69:5000
      OWNER_KEY: SuperSafeNodeOwnerKey
    networks:
      default:
        ipv4_address: 10.0.0.65

  whirlpool:
    extends:
      file: compose.base.yml
      service: whirlpool
    environment:
      ADDRESS: 10.0.0.87
      OWNER_KEY: SuperSafeNodeOwnerKey
    networks:
      default:
        ipv4_address: 10.0.0.87

  echo:
    extends:
      file: compose.base.yml
      service: echo
    environment:
      BUFFER_SIZE: 8192
      ECHO_PORT: 5000
    networks:
      default:
        ipv4_address: 10.0.0.69

networks:
  default:
    driver: bridge
    name: sea-int
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
