# This file defines basic Docker images for integration testing.
# Unlike images from "default", these contain additional dependencies, settings, etc.
# They also will not be destroyed and recreated during tests - for speedup.
# They are also reused in other Dockerfile targets in this directory.

services:
  algae:
    privileged: true
    init: true
    build:
      dockerfile: viridian/algae/docker/Dockerfile.algae
      context: ../../..
      target: default-routed
    env_file:
      - test.conf.env
    environment:
      RUNNING_IN_CI: ${RUNNING_IN_CI:-0}
      SEASIDE_CERTIFICATE_PATH: /seaside/viridian
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - ../certificates/viridian:/seaside/viridian:rw

  whirlpool:
    privileged: true
    init: true
    build:
      dockerfile: caerulean/whirlpool/Dockerfile
      context: ../../..
      target: default-routed
    env_file:
      - test.conf.env
    environment:
      RUNNING_IN_CI: ${RUNNING_IN_CI:-0}
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - ../certificates:/seaside/caerulean/certificates:rw

  echo:
    privileged: true
    init: true
    build:
      dockerfile: viridian/algae/docker/Dockerfile.echo
      context: ../../..
      target: default-routed
    env_file:
      - test.conf.env
    environment:
      LOG_LEVEL: DEBUG

  router:
    privileged: true
    init: true
    build:
      dockerfile: viridian/algae/docker/Dockerfile.router
      context: ../../..
      target: default
    env_file:
      - test.conf.env
