version: "3.9"

services:
  algae:
    image: algae-latest
    container_name: algae
    privileged: true
    build:
      dockerfile: viridian/algae/docker/Dockerfile.algae
      context: ../../..
    environment:
      LOG_LEVEL: DEBUG
      BUFFER_SIZE: 8192  # Buffer for echo server message storing
      LOCAL_ECHO_PORT: 5000  # Port for echo server accessing
      OWNER_KEY: SuperSafeNodeOwnerKey  # Whirlpool node owner key

  whirlpool:
    image: whirlpool-latest
    container_name: whirlpool
    privileged: true
    build:
      dockerfile: caerulean/whirlpool/Dockerfile
      context: ../../..
    environment:
      LOG_LEVEL: DEBUG
      OWNER_KEY: SuperSafeNodeOwnerKey  # Whirlpool node owner key

  echo:
    image: seaside-echo-latest
    container_name: seaside-echo
    build:
      dockerfile: docker/Dockerfile.echo
      context: ..
    environment:
      BUFFER_SIZE: 8192  # Buffer for echo server message storing
      ECHO_PORT: 5000  # Port for echo server accessing
