version: "3.9"

services:
  algae:
    extends:
      file: compose.base.yml
      service: algae
    environment:
      ADDRESS: 10.0.0.87
      LOCAL_ECHO: 10.0.0.69
    networks:
      default:
        ipv4_address: 10.0.0.65

  whirlpool:
    extends:
      file: compose.base.yml
      service: whirlpool
    environment:
      ADDRESS: 10.0.0.87
    networks:
      default:
        ipv4_address: 10.0.0.87

networks:
  default:
    driver: host
    name: sea-int
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
