version: "3.9"

services:
  algae:
    image: seaside-algae-smoke-remote
    container_name: seaside-algae
    extends:
      file: compose.base.yml
      service: algae
    build:
      args:
        NETWORK_GATEWAY: 10.65.0.100
    networks:
      sea-client:
        ipv4_address: 10.65.0.65
    depends_on:
      whirlpool:
        condition: service_healthy

  whirlpool:
    image: seaside-whirlpool-smoke-remote
    extends:
      file: compose.base.yml
      service: whirlpool
    build:
      args:
        NETWORK_GATEWAY: 10.87.0.1
    environment:
      SEASIDE_EXTERNAL: 10.87.0.87
    networks:
      sea-client:
        ipv4_address: 10.65.0.87
      sea-server:
        ipv4_address: 10.87.0.87


networks:
  sea-client:
    ipam:
      config:
        - subnet: 10.65.0.0/24
          gateway: 10.65.0.1
  sea-server:
    ipam:
      config:
        - subnet: 10.87.0.0/24
          gateway: 10.87.0.1
