services:
  whirlpool-base:
    image: whirlpool-standalone
    container_name: whirlpool-standalone
    extends:
      file: compose.base.yml
      service: whirlpool
    build:
      target: default-certified
      args:
        SEASIDE_ADDRESS: ${SEASIDE_ADDRESS_ARG}

  whirlpool-bridge:
    extends: whirlpool-base
    networks:
      sea-net:
        ipv4_address: 10.0.0.87

  whirlpool-host:
    extends: whirlpool-base
    network_mode: host


networks:
  sea-net:
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
