version: "3.9"

services:
  algae:
    extends:
      file: compose.base.yml
      service: algae
    environment:
      LOG_LEVEL: DEBUG
      BUFFER_SIZE: 8192
      NODE_ADDR: 87.0.0.87
      LOCAL_ADDR: 87.0.0.65
      SEA_PORT: 8542
      LOCAL_ECHO: 69.0.0.69:5000
      OWNER_KEY: SuperSafeNodeOwnerKey
    networks:
      sea_int:
        ipv4_address: 87.0.0.65

  whirlpool:
    extends:
      file: compose.base.yml
      service: whirlpool
    environment:
      LOG_LEVEL: DEBUG
      ADDRESS: 87.0.0.87
      EXTERNAL: 69.0.0.87
      OWNER_KEY: SuperSafeNodeOwnerKey
    networks:
      sea_int:
        ipv4_address: 87.0.0.87
      sea_ext:
        ipv4_address: 69.0.0.87

  echo:
    extends:
      file: compose.base.yml
      service: echo
    environment:
      BUFFER_SIZE: 8192
      ECHO_PORT: 5000
    networks:
      sea_ext:
        ipv4_address: 69.0.0.69

networks:
  sea_int:
    internal: true
    ipam:
      config:
        - subnet: 87.0.0.0/24
          gateway: 87.0.0.1
  sea_ext:
    internal: true
    ipam:
      config:
        - subnet: 69.0.0.0/24
          gateway: 69.0.0.1
