name: seaside-algae-standalone

services:
  int-router:
    container_name: seaside-internal-router
    extends:
      file: compose.base.yml
      service: router
    networks:
      sea-cli-int:
        ipv4_address: 10.82.0.100
      sea-rout-int:
        ipv4_address: 10.87.82.100

  whirlpool:
    image: seaside-whirlpool-reef
    extends:
      file: compose.base.yml
      service: whirlpool
    build:
      args:
        NETWORK_GATEWAY: 10.87.42.100
        SEASIDE_ADDRESS: 10.87.82.87
    environment:
      SEASIDE_LOG_LEVEL: DEBUG
    networks:
      sea-rout-int:
        ipv4_address: 10.87.82.87
      sea-rout-ext:
        ipv4_address: 10.87.42.87

  ext-router:
    container_name: seaside-external-router
    extends:
      file: compose.base.yml
      service: router
    networks:
      sea-rout-ext:
        ipv4_address: 10.87.42.100
      sea-serv-ext:
        ipv4_address: 10.42.0.100

  echo:
    container_name: seaside-echo
    extends:
      file: compose.base.yml
      service: echo
    build:
      args:
        NETWORK_GATEWAY: 10.42.0.100
    networks:
      sea-serv-ext:
        ipv4_address: 10.42.0.42


networks:
  sea-cli-int:
    ipam:
      config:
        - subnet: 10.82.0.0/24
          gateway: 10.82.0.1
  sea-rout-int:
    ipam:
      config:
        - subnet: 10.87.82.0/24
          gateway: 10.87.82.1
  sea-rout-ext:
    ipam:
      config:
        - subnet: 10.87.42.0/24
          gateway: 10.87.42.1
  sea-serv-ext:
    ipam:
      config:
        - subnet: 10.42.0.0/24
          gateway: 10.42.0.1
