name: seaside-algae-remote

services:
  algae:
    image: seaside-algae-remote
    container_name: seaside-algae
    extends:
      file: compose.base.yml
      service: algae
    build:
      args:
        RUNNING_TEST_FILE: test_remote.py
        NETWORK_GATEWAY: 10.0.0.100
    environment:
      SEASIDE_ADDRESS: 10.0.0.87
    networks:
      sea-net:
        ipv4_address: 10.0.0.65
    depends_on:
      whirlpool:
        condition: service_healthy

  whirlpool:
    image: seaside-whirlpool-remote
    extends:
      file: compose.base.yml
      service: whirlpool
    build:
      args:
        NETWORK_GATEWAY: 10.0.0.1
        SEASIDE_ADDRESS: 10.0.0.87
    environment:
      SEASIDE_EXTERNAL: 10.0.0.87
    networks:
      sea-net:
        ipv4_address: 10.0.0.87


networks:
  sea-net:
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
