FROM alpine:3.18 as test

RUN apk add --no-cache iptables
ENTRYPOINT echo 1 > /proc/sys/net/ipv4/ip_forward && \
    iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE && \
    iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE && \
    iptables -A FORWARD -i eth0 -j ACCEPT && \
    iptables -A FORWARD -i eth1 -j ACCEPT && \
    sleep infinity
