services:
  reef:
    container_name: seaside-reef
    build:
      context: ../..
      dockerfile: viridian/reef/docker/Dockerfile
      args:
        NETWORK_GATEWAY: 10.65.0.100
    environment:
      SEASIDE_ADDRESS: 10.87.65.87
      LOCAL_ADDRESS: 10.65.0.65
      ECHO_ADDRESS: 10.42.0.42
      SEASIDE_CONNECTION_TIMEOUT: 30.0
    networks:
      sea-cli-int:
        ipv4_address: 10.65.0.65

  int-router:
    image: seaside-router-smoke
    privileged: true
    build:
      context: ../../..
      dockerfile: viridian/algae/docker/Dockerfile.router
      target: smoke
    container_name: seaside-internal-router
    networks:
      sea-cli-int:
        ipv4_address: 10.65.0.100
      sea-rout-int:
        ipv4_address: 10.87.65.100

  whirlpool:
    image: seaside-reef-whirlpool-local
    container_name: seaside-whirlpool
    privileged: true
    build:
      context: ../../..
      dockerfile: viridian/algae/docker/Dockerfile.whirlpool
      target: smoke
      args:
        NETWORK_GATEWAY: 10.87.42.100
    environment:
      SEASIDE_PAYLOAD_OWNER: super_secret_owner_payload_data
      SEASIDE_PAYLOAD_VIRIDIAN: super_secret_user_payload_data
      SEASIDE_ADDRESS: 10.87.65.87
      SEASIDE_EXTERNAL: 10.87.42.87
      SEASIDE_CTRLPORT: 8587
      SEASIDE_LOG_LEVEL: DEBUG
    volumes:
      - ./certificates:/seaside/caerulean/certificates
    networks:
      sea-rout-int:
        ipv4_address: 10.87.65.87
      sea-rout-ext:
        ipv4_address: 10.87.42.87

  ext-router:
    image: seaside-router-smoke
    privileged: true
    build:
      context: ../../..
      dockerfile: viridian/algae/docker/Dockerfile.router
      target: smoke
    container_name: seaside-external-router
    networks:
      sea-rout-ext:
        ipv4_address: 10.87.42.100
      sea-serv-ext:
        ipv4_address: 10.42.0.100

  echo:
    image: seaside-echo-smoke
    container_name: seaside-echo
    privileged: true
    build:
      context: ../../..
      dockerfile: viridian/algae/docker/Dockerfile.echo
      target: smoke
      args:
        NETWORK_GATEWAY: 10.42.0.100
    environment:
      LOG_LEVEL: DEBUG
      BUFFER_SIZE: 8192
      ECHO_PORT: 5000
    networks:
      sea-serv-ext:
        ipv4_address: 10.42.0.42


networks:
  sea-cli-int:
    ipam:
      config:
        - subnet: 10.65.0.0/24
          gateway: 10.65.0.1
  sea-rout-int:
    ipam:
      config:
        - subnet: 10.87.65.0/24
          gateway: 10.87.65.1
  sea-rout-ext:
    ipam:
      config:
        - subnet: 10.87.42.0/24
          gateway: 10.87.42.1
  sea-serv-ext:
    ipam:
      config:
        - subnet: 10.42.0.0/24
          gateway: 10.42.0.1
