name: seaside-reef

services:
  int-router:
    container_name: seaside-internal-router
    extends:
      file: ../../../viridian/algae/docker/compose.base.yml
      service: router
    env_file:
      - host.env
    networks:
      sea-cli-int:
        ipv4_address: 10.82.0.100
      sea-rout-int:
        ipv4_address: 10.87.82.100

  whirlpool:
    image: seaside-whirlpool-reef
    extends:
      file: ../../../viridian/algae/docker/compose.base.yml
      service: whirlpool
    build:
      args:
        NETWORK_GATEWAY: 10.87.42.100
    env_file:
      - host.env
    environment:
      SEASIDE_PAYLOAD_OWNER: super_secret_owner_payload_data
      SEASIDE_EXTERNAL: 10.87.42.87
      SEASIDE_LOG_LEVEL: DEBUG
    networks:
      sea-rout-int:
        ipv4_address: 10.87.82.87
      sea-rout-ext:
        ipv4_address: 10.87.42.87

  ext-router:
    container_name: seaside-external-router
    extends:
      file: ../../../viridian/algae/docker/compose.base.yml
      service: router
    env_file:
      - host.env
    networks:
      sea-rout-ext:
        ipv4_address: 10.87.42.100
      sea-serv-ext:
        ipv4_address: 10.42.0.100

  echo:
    container_name: seaside-echo
    extends:
      file: ../../../viridian/algae/docker/compose.base.yml
      service: echo
    build:
      args:
        NETWORK_GATEWAY: 10.42.0.100
    env_file:
      - host.env
    networks:
      sea-serv-ext:
        ipv4_address: 10.42.0.42


networks:
  sea-cli-int:
    ipam:
      config:
        - subnet: 10.82.0.0/24
          gateway: 10.82.0.1
  sea-rout-int:
    ipam:
      config:
        - subnet: 10.87.82.0/24
          gateway: 10.87.82.1
  sea-rout-ext:
    ipam:
      config:
        - subnet: 10.87.42.0/24
          gateway: 10.87.42.1
  sea-serv-ext:
    ipam:
      config:
        - subnet: 10.42.0.0/24
          gateway: 10.42.0.1
