[tool.poetry]
name = "SeasideVPN"
version = "0.0.1"
description = "A simple PPTP UDP VPN system"
license = "MIT"
authors = [
    "Alexander Sergeev <alexander.sergeev@onmail.com>",
]

readme = "README.md"
repository = "https://github.com/pseusys/SeasideVPN"
keywords = ["open-source", "udp", "distributed", "vpn", "client-server", "pptp", "p2p-network"]

packages = [
    { include = "sources" },
    { include = "scripts" },
    { include = "tests" },
]



[tool.poetry.dependencies]
python = ">=3.8,<3.12"
colorama = "^0.4.6"

[tool.poetry.group.client.dependencies]
pyroute2 = "^0.7.9"
python-iptables = "^1.0.1"
betterproto = "^2.0.0b6"
pycryptodome = "^3.18.0"

[tool.poetry.group.devel.dependencies]
pytest = "^7.3.1"
pythonping = "^1.1.4"
pytest-timeout = "^2.2.0"
pytest-dependency = "^0.5.1"

[tool.poetry.group.script.dependencies]
mypy = "^1.3.0"
flake8 = "^3.9.2"
black = "^20.8b1"
isort = "^5.11.0"
pyinstaller = "^5.11.0"
python-on-whales = "^0.65.0"
betterproto = { version = "^2.0.0b6", extras = ["compiler"] }


[tool.poetry.scripts]
generate = "scripts.process:generate"
lint = "scripts.codestyle:lint"
format = "scripts.codestyle:format"
test_unit = "scripts.test:test_unit"
test_integration = "scripts.test:test_integration"
test_smoke = "scripts.test:test_smoke"
test_all = "scripts.test:test_all"
compile = "scripts.process:compile"
execute = "scripts.process:execute"
clean = "scripts.process:clean"



[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"



[tool.isort]
profile = "black"
