[tool.poetry]
name = "SeasideVPN"
version = "0.0.2"
description = "A simple PPTP UDP VPN system"
license = "MIT"
authors = [
    "Alexander Sergeev <alexander.sergeev@onmail.com>",
]

readme = "README.md"
repository = "https://github.com/pseusys/SeasideVPN"
keywords = ["open-source", "udp", "distributed", "vpn", "client-server", "pptp", "p2p-network"]

packages = [
    { include = "sources" },
    { include = "scripts" },
    { include = "tests" },
]



[tool.poetry.dependencies]
python = ">=3.8.1,<3.13"
colorama = "^0.4.6"

[tool.poetry.group.client.dependencies]
pyroute2 = "^0.7.9"
python-iptables = "^1.0.1"
betterproto = "^2.0.0b6"
pycryptodome = "^3.18.0"

[tool.poetry.group.devel.dependencies]
pytest = "^8.3.2"
pythonping = "^1.1.4"
pytest-asyncio = "^0.24.0"
pytest-timeout = "^2.2.0"
pytest-dependency = "^0.6.0"

[tool.poetry.group.script.dependencies]
mypy = "^1.3.0"
flake8 = "^7.1.0"
black = "^24.4.2"
isort = "^5.11.0"
pyinstaller = "^6.9.0"
python-on-whales = "^0.73.0"
grpcio-tools = "^1.62.0"
PyYAML = "^6.0.2"
betterproto = { version = "^2.0.0b6", extras = ["compiler"] }


[tool.poe.poetry_hooks]
post_install = "generate"


[tool.poe.tasks]
generate.script = "__init__:generate"
lint.script = "__init__:lint"
format.script = "__init__:format"
test-unit.script = "scripts:test_unit"
test-integration.script = "scripts:test_integration"
test-smoke.script = "scripts:test_smoke"
test-local.script = "scripts:test_local"
test-remote.script = "scripts:test_remote"
test-domain.script = "scripts:test_domain"
test-all.script = "scripts:test_all"
compile.script = "__init__:compile"
execute.script = "__init__:execute"
bundle.script = "__init__:bundle"
clean.script = "__init__:clean"
help.script = "__init__:help"



[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"



[tool.isort]
profile = "black"
