[tool.poetry]
name = "SeasideVPN"
version = "0.0.1"
description = "A simple PPTP UDP VPN system"
license = "MIT"
authors = [
    "Alexander Sergeev <alexander.sergeev@onmail.com>",
]

readme = "README.md"
repository = "https://github.com/pseusys/SeasideVPN"
keywords = ["open-source", "udp", "distributed", "vpn", "client-server", "pptp", "p2p-network"]

packages = [
    { include = "sources" },
    { include = "scripts" },
    { include = "tests" },
]



[tool.poetry.dependencies]
python = ">=3.8,<3.12"
colorama = "^0.4.6"
pyroute2 = "^0.7.9"
protobuf = "^4.24.4"
pycryptodome = "^3.18.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"

[tool.poetry.group.devel]
optional = true

[tool.poetry.group.devel.dependencies]
mypy = "^1.3.0"
flake8 = "^3.9.2"
black = "^20.8b1"
isort = "^5.11.0"
pyinstaller = "^5.11.0"
python-on-whales = "^0.65.0"


[tool.poetry.scripts]
generate = "scripts.process:generate"
lint = "scripts.codestyle:lint"
format = "scripts.codestyle:format"
test = "scripts.test:test"
compile = "scripts.process:compile"
clean = "scripts.process:clean"



[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"



[tool.isort]
profile = "black"
