FROM golang:1.20-alpine3.17 as builder

WORKDIR /seaside/caerulean

RUN apk add --no-cache build-base gmp-dev
RUN go install golang.org/x/lint/golint@latest

COPY go.mod ./
COPY crypto ./crypto
COPY generated ./generated
COPY sources ./sources
COPY tests ./tests
COPY tunnel ./tunnel
COPY users ./users
COPY utils ./utils

RUN go mod tidy
