[package]
name = "SeasideVPN-Reef"
version = "0.0.3"
edition = "2021"
description = "A production-ready SeasideVPN client for Linux and Windows"
authors = [
    "Alexander Sergeev <alexander.sergeev@onmail.com>"
]



[dependencies]
rand = "^0.8.5"
prost = "^0.13.3"
log = "^0.4.22"
env_logger = "^0.11.5"
prost-types = "^0.13.3"
gethostname = "^0.5.0"
chacha20poly1305 = "^0.10.1"
simple-error = "^0.3.1"
tun = { version = "^0.7.1", features = ["async"] }
tonic = { version = "^0.12.3", features = ["tls", "tls-webpki-roots"] }
tokio = { version = "^1.41.0", features = ["macros", "rt-multi-thread", "process", "signal", "net"] }
structopt = { version = "^0.3.26", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
neli = "^0.6.4"
iptables = "^0.5.1"



[features]
cli-exec = ["structopt"]

[build-dependencies]
tonic-build = "^0.12.3"
protoc-prebuilt = "^0.3.0"

[dev-dependencies]
regex = "^1.11.1"



[lib]
name = "reeflib"
path = "src/lib/mod.rs"

[[bin]]
name = "cli"
path = "src/cli.rs"
required-features = ["cli-exec"] 
